AUV: True
serial: 
  enabled: False
  serial_port: /dev/ttyUSB0
  serial_baudrate: 115200
  serial_timeout: 0.1
camera:
  camera_ip: '192.168.1.148'
  camera_port: 8080
  camera_fps: 30
  camera_resolution: (1280, 720)
orin:
  orin_ip: '192.168.1.148'
  